<?xml version="1.0" encoding="ISO-8859-1"?>
<definitions xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"
    xmlns:tns="urn:arnleadservicewsdl"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    targetNamespace="urn:serviceuserwsdl">

    <types>
        <xsd:schema targetNamespace="urn:userwsdl">
            <xsd:import namespace="http://schemas.xmlsoap.org/soap/encoding/" />
            <xsd:import namespace="http://schemas.xmlsoap.org/wsdl/" />
        </xsd:schema>
    </types>

    <message name="userRequest">
        <part name="names" type="xsd:string" />
        <part name="movil" type="xsd:string" />
        <part name="email" type="xsd:string" />
        <part name="document" type="xsd:string" />
    </message>

    <message name="userResponse">
        <part name="response" type="xsd:string" />
    </message>

    <portType name="userwsdlPortType">
        <operation name="createuser">
            <documentation>User</documentation>
            <input message="tns:userRequest"/>
            <output message="tns:userResponse"/>
        </operation>
    </portType>

    <binding name="userwsdlBinding" type="tns:userwsdlPortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="createuser">
            <soap:operation soapAction="urn:arnleadservicewsdl#createuser" style="rpc"/>

            <input>
                <soap:body use="encoded" namespace="urn:userwsdl"
                           encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
            </input>

            <output>
                <soap:body use="encoded" namespace="urn:userwsdl"
                           encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
            </output>
        </operation>
    </binding>

    <service name="userwsdl">
        <port name="userwsdlPort" binding="tns:userwsdlBinding">
            <soap:address location="http://wallet.pt.com/index.php/user/soap"/>
        </port>
    </service>
</definitions>